RubyOnRails_seedProject/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'miscellaneous#blank_page'
  # Miscellaneous
  get 'miscellaneous/login',
      to: 'miscellaneous#login',
      as: :miscellaneous_login
  get 'miscellaneous/register',
      to: 'miscellaneous#register',
      as: :miscellaneous_register
  get 'miscellaneous/forgot_password',
      to: 'miscellaneous#forgot_password',
      as: :miscellaneous_forgot_password
  get 'miscellaneous/locked_screen',
      to: 'miscellaneous#locked_screen',
      as: :miscellaneous_locked_screen

  # AJAX
  get 'ajax/email_compose', to: 'ajax#email_compose', as: :ajax_email_compose
  get 'ajax/email_list', to: 'ajax#email_list', as: :ajax_email_list
  get 'ajax/email_opened', to: 'ajax#email_opened', as: :ajax_email_opened
  get 'ajax/email_reply', to: 'ajax#email_reply', as: :ajax_email_reply
  get 'ajax/demo_widget', to: 'ajax#demo_widget', as: :ajax_demo_widget
  get 'ajax/data_list.json', to: 'ajax#data_list', as: :ajax_data_list
  get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks', to: 'ajax#notify_tasks', as: :ajax_notify_tasks

  # Misc methods
  get '/home/set_locale', to: 'home#set_locale', as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'
end

RubyOnRails_seedProject/app/models/application_record.rb
# :nodoc:
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RubyOnRails_seedProject/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def remember_me
    (super == nil) ? '1' : super
    end
end

RubyOnRails_seedProject/app/controllers/ajax_controller.rb
# AJAX helpers
class AjaxController < ApplicationController
  layout false

  def email_list
  end

  def email_compose
  end

  def email_opened
  end

  def email_reply
  end

  def demo_widget
  end

  def data_list
  end

  def notify_mail
  end

  def notify_notifications
  end

  def notify_tasks
  end
end

RubyOnRails_seedProject/app/controllers/application_controller.rb
# :nodoc:
class ApplicationController < ActionController::Base
  before_filter :set_gettext_locale
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

RubyOnRails_seedProject/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def set_locale
    session[:locale] = params[:locale]
    redirect_to :back
  end
end

RubyOnRails_seedProject/app/controllers/miscellaneous_controller.rb
class MiscellaneousController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:register, :forgot_password]

  def login
    @simulate_no_user = true
  end

  def register
    @simulate_no_user = true
  end

  def forgot_password
    @simulate_no_user = true
  end

  def locked_screen
    @simulate_no_user = true
    @lock_screen = true
  end

  def blank_page
  end
end

RubyOnRails_seedProject/app/helpers/application_helper.rb
# :nodoc:
module ApplicationHelper
  def left_menu
    left_menu_entries(left_menu_content)
  end

  private

  def selected_locale
    locale = FastGettext.locale
    locale_list.detect {|entry| entry[:locale] == locale}
  end

  def locale_list
    [
      {
        flag: 'us',
        locale: 'en',
        name: 'English (US)',
        alt_name: 'United States'
      },
      {
        flag: 'fr',
        locale: 'fr',
        name: 'Français',
        alt_name: 'France'
      },
      {
        flag: 'es',
        locale: 'es',
        name: 'Español',
        alt_name: 'Spanish'
      },
      {
        flag: 'de',
        locale: 'de',
        name: 'Deutsch',
        alt_name: 'German'
      },
      {
        flag: 'jp',
        locale: 'ja',
        name: '日本語',
        alt_name: 'Japan'
      },
      {
        flag: 'cn',
        locale: 'zh',
        name: '中文',
        alt_name: 'China'
      },
      {
        flag: 'it',
        locale: 'it',
        name: 'Italiano',
        alt_name: 'Italy'
      },
      {
        flag: 'pt',
        locale: 'pt',
        name: 'Portugal',
        alt_name: 'Portugal'
      },
      {
        flag: 'ru',
        locale: 'ru',
        name: 'Русский язык',
        alt_name: 'Russia'
      },
      {
        flag: 'kr',
        locale: 'kr',
        name: '한국어',
        alt_name: 'Korea'
      },
    ]
  end

  def left_menu_entries(entries = [])
    output = ''
    entries.each do |entry|
      children_selected = entry[:children] &&
        entry[:children].any? {|child| current_page?(child[:href]) }
      entry_selected =  current_page?(entry[:href])
      li_class =
      case
        when children_selected
          'open'
        when entry_selected
          'active'
      end
      output +=
        content_tag(:li, class: li_class) do
          subentry = ''
          subentry +=
            link_to entry[:href], title: entry[:title], class: entry[:class], target: entry[:target] do
              link_text = ''
              link_text += entry[:content].html_safe
              if entry[:children]
                if children_selected
                  link_text += '<b class="collapse-sign"><em class="fa fa-minus-square-o"></em></b>'
                else
                  link_text += '<b class="collapse-sign"><em class="fa fa-plus-square-o"></em></b>'
                end
              end

              link_text.html_safe
            end
          if entry[:children]
            if children_selected
              ul_style = 'display: block'
            else
              ul_style = ''
            end
            subentry +=
              "<ul style='#{ul_style}'>" +
                left_menu_entries(entry[:children]) +
                "</ul>"
          end

          subentry.html_safe
        end
    end
    output.html_safe
  end

  def left_menu_content
    [
      {
        href: root_path,
        title: _('blank'),
        content: "<i class='fa fa-lg fa-fw fa-home'></i> <span class='menu-item-parent'>" + _('Blank') + "</span>",
      },
    ]
  end

end

RubyOnRails_seedProject/app/views/layouts/_footer.html.erb
<div class="page-footer">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <span class="txt-color-white">SmartAdmin 1.8.x <span class="hidden-xs"> - Web Application Framework</span> © 2014-2015</span>
    </div>

  </div>
</div>

RubyOnRails_seedProject/app/views/layouts/_header.html.erb
<header id="header">
  <div id="logo-group">

    <!-- PLACE YOUR LOGO HERE -->
    <span id="logo"> <%= image_tag 'logo.png', alt: 'SmartAdmin' %> </span>
    <!-- END LOGO PLACEHOLDER -->

    <% if current_user && !@simulate_no_user %>
      <!-- Note: The activity badge color changes when clicked and resets the number to 0
      Suggestion: You may want to set a flag when this happens to tick off all checked messages / notifications -->
      <span id="activity" class="activity-dropdown"> <i class="fa fa-user"></i> <b class="badge"> 21 </b> </span>

      <!-- AJAX-DROPDOWN : control this dropdown height, look and feel from the LESS variable file -->
      <div class="ajax-dropdown">

        <!-- the ID links are fetched via AJAX to the ajax container "ajax-notifications" -->
        <div class="btn-group btn-group-justified" data-toggle="buttons">
          <label class="btn btn-default">
            <input type="radio" name="activity" id="<%= ajax_notify_mail_path %>">
            <%= _('Msgs') %> (14) </label>
          <label class="btn btn-default">
            <input type="radio" name="activity" id="<%= ajax_notify_notifications_path %>">
            <%= _('notify') %> (3) </label>
          <label class="btn btn-default">
            <input type="radio" name="activity" id="<%= ajax_notify_tasks_path %>">
            <%= _('Tasks') %> (4) </label>
        </div>

        <!-- notification content -->
        <div class="ajax-notifications custom-scroll">

          <div class="alert alert-transparent">
            <h4>Click a button to show messages here</h4>
            This blank page message helps protect your privacy, or you can show the first message here automatically.
          </div>

          <i class="fa fa-lock fa-4x fa-border"></i>

        </div>
        <!-- end notification content -->

        <!-- footer: refresh area -->
            <span> Last updated on: 12/12/2013 9:43AM
              <button type="button" data-loading-text="<i class='fa fa-refresh fa-spin'></i> Loading..." class="btn btn-xs btn-default pull-right">
                <i class="fa fa-refresh"></i>
              </button>
            </span>
        <!-- end footer -->

      </div>
      <!-- END AJAX-DROPDOWN -->
    <% end %>
  </div>
  <%= yield :top_right %>

  <% if current_user && !@simulate_no_user %>
    <!-- projects dropdown -->
    <div class="project-context hidden-xs">

      <span class="label">Projects:</span>
      <span class="project-selector dropdown-toggle" data-toggle="dropdown"><%= _('Recent projects') %> <i class="fa fa-angle-down"></i></span>

      <!-- Suggestion: populate this list with fetch and push technique -->
      <ul class="dropdown-menu">
        <li>
          <a href="javascript:void(0);">Online e-merchant management system - attaching integration with the iOS</a>
        </li>
        <li>
          <a href="javascript:void(0);">Notes on pipeline upgradee</a>
        </li>
        <li>
          <a href="javascript:void(0);">Assesment Report for merchant account</a>
        </li>
        <li class="divider"></li>
        <li>
          <a href="javascript:void(0);"><i class="fa fa-power-off"></i> Clear</a>
        </li>
      </ul>
      <!-- end dropdown-menu-->

    </div>
    <!-- end projects dropdown -->

    <!-- pulled right: nav area -->
    <div class="pull-right">

      <!-- collapse menu button -->
      <div id="hide-menu" class="btn-header pull-right">
        <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu"><i class="fa fa-reorder"></i></a> </span>
      </div>
      <!-- end collapse menu -->

      <!-- #MOBILE -->
      <!-- Top menu profile link : this shows only when top menu is active -->
      <ul id="mobile-profile-img" class="header-dropdown-list hidden-xs padding-5">
        <li class="">
          <a href="#" class="dropdown-toggle no-margin userdropdown" data-toggle="dropdown">
            <%= image_tag 'avatars/sunny.png', alt: 'John Doe', class: 'online' %>
          </a>
          <ul class="dropdown-menu pull-right">
            <li>
              <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0"><i class="fa fa-cog"></i> Setting</a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="profile.html" class="padding-10 padding-top-0 padding-bottom-0"> <i class="fa fa-user"></i> <u>P</u>rofile</a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="toggleShortcut"><i class="fa fa-arrow-down"></i> <u>S</u>hortcut</a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="launchFullscreen"><i class="fa fa-arrows-alt"></i> Full <u>S</u>creen</a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="login.html" class="padding-10 padding-top-5 padding-bottom-5" data-action="userLogout"><i class="fa fa-sign-out fa-lg"></i> <strong><u>L</u>ogout</strong></a>
            </li>
          </ul>
        </li>
      </ul>

      <!-- logout button -->
      <div id="logout" class="btn-header transparent pull-right">
        <span>
          <%= link_to(destroy_user_session_path, title: 'Sign Out', data: {action: 'userLogout', 'logout-msg' => 'You can improve your security further after logging out by closing this opened browser'}) do %>
            <i class="fa fa-sign-out"></i>
          <% end %>
        </span>
      </div>
      <!-- end logout button -->

      <!-- search mobile button (this is hidden till mobile view port) -->
      <div id="search-mobile" class="btn-header transparent pull-right">
        <span> <a href="javascript:void(0)" title="Search"><i class="fa fa-search"></i></a> </span>
      </div>
      <!-- end search mobile button -->

      <!-- input: search field -->
      <form action="<%= root_path %>" class="header-search pull-right">
        <input id="search-fld"  type="text" name="param" placeholder="<%= _('Find reports and more') %>" data-autocomplete='[
            "ActionScript",
            "AppleScript",
            "Asp",
            "BASIC",
            "C",
            "C++",
            "Clojure",
            "COBOL",
            "ColdFusion",
            "Erlang",
            "Fortran",
            "Groovy",
            "Haskell",
            "Java",
            "JavaScript",
            "Lisp",
            "Perl",
            "PHP",
            "Python",
            "Ruby",
            "Scala",
            "Scheme"]'>
        <button type="submit">
          <i class="fa fa-search"></i>
        </button>
        <a href="javascript:void(0);" id="cancel-search-js" title="Cancel Search"><i class="fa fa-times"></i></a>
      </form>
      <!-- end input: search field -->

      <!-- fullscreen button -->
      <div id="fullscreen" class="btn-header transparent pull-right">
        <span> <a href="javascript:void(0);" data-action="launchFullscreen" title="Full Screen"><i class="fa fa-arrows-alt"></i></a> </span>
      </div>
      <!-- end fullscreen button -->

      <!-- multiple lang dropdown : find all flags in the flags page -->
      <%= render 'layouts/locale_select' %>
      <!-- end multiple lang -->

    </div>
    <!-- end pulled right: nav area -->
  <% end %>

</header>

RubyOnRails_seedProject/app/views/layouts/_left_panel.html.erb
<aside id="left-panel">

  <!-- User info -->
  <div class="login-info">
				<span> <!-- User image size is adjusted inside CSS, it should stay as it -->

					<a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
            <%= image_tag 'avatars/sunny.png', alt: 'me', class: 'online' %>
            <span>
							john.doe
						</span>
            <i class="fa fa-angle-down"></i>
          </a>

				</span>
  </div>
  <!-- end user info -->

  <!-- NAVIGATION : This navigation is also responsive-->
  <nav>
    <!--
    NOTE: Notice the gaps after each icon usage <i></i>..
    Please note that these links work a bit different than
    traditional href="" links. See documentation for details.
    -->

    <ul>
      <%= left_menu %>
    </ul>
  </nav>


			<span class="minifyme" data-action="minifyMenu">
				<i class="fa fa-arrow-circle-left hit"></i>
			</span>

</aside>

RubyOnRails_seedProject/app/views/layouts/_locale_select.html.erb
<% @selected_locale = selected_locale %>
<ul class="header-dropdown-list hidden-xs">
  <li>
    <%= link_to '#', class: 'dropdown-toggle', data: {toggle: 'dropdown'} do %>
      <%= image_tag "blank.gif", class: "flag flag-#{@selected_locale[:flag]}", alt: @selected_locale[:alt_name] %> <span> <%= @selected_locale[:name] %> </span> <i class="fa fa-angle-down"></i>
  <% end %>
    <ul class="dropdown-menu pull-right">
      <% locale_list.each do |locale| %>
        <li class="<%= 'active' if locale[:locale] == @selected_locale[:locale] %>">
          <%= link_to home_set_locale_path(locale: locale[:locale]) do %>
            <%= image_tag "blank.gif", class: "flag flag-#{locale[:flag]}", alt: locale[:alt_name] %> <%= locale[:name] %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </li>
</ul>

RubyOnRails_seedProject/app/views/layouts/_scripts.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    pageSetUp();
  })
</script>

RubyOnRails_seedProject/app/views/layouts/_tiles.html.erb
<div id="shortcut">
  <ul>
    <li>
      <%= link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-blue' do %>
        <span class="iconbox"> <i class="fa fa-envelope fa-4x"></i> <span>Mail <span class="label pull-right bg-color-darken">14</span></span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-orangeDark' do %>
        <span class="iconbox"> <i class="fa fa-calendar fa-4x"></i> <span>Calendar</span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-purple' do %>
        <span class="iconbox"> <i class="fa fa-map-marker fa-4x"></i> <span>Maps</span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-blueDark' do %>
        <span class="iconbox"> <i class="fa fa-book fa-4x"></i> <span>Invoice <span class="label pull-right bg-color-darken">99</span></span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-greenLight' do %>
        <span class="iconbox"> <i class="fa fa-picture-o fa-4x"></i> <span>Gallery </span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to root_path, class: 'jarvismetro-tile big-cubes selected bg-color-pinkDark' do %>
        <span class="iconbox"> <i class="fa fa-user fa-4x"></i> <span>My Profile </span> </span>
      <% end %>
    </li>
  </ul>
</div>

RubyOnRails_seedProject/app/views/miscellaneous/blank_page.html.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">

    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li>Home</li>
      <li>Blank</li>
    </ol>
    <!-- end breadcrumb -->

    <!-- You can also add more buttons to the
    ribbon for further usability

    Example below:

    <span class="ribbon-button-alignment pull-right" style="margin-right:25px">
      <a href="#" id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa fa-grid"></i> Change Grid</a>
      <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa fa-plus"></i> Add</span>
      <button id="search" class="btn btn-ribbon" data-title="search"><i class="fa fa-search"></i> <span class="hidden-mobile">Search</span></button>
    </span> -->

  </div>
  <!-- END RIBBON -->
<% end %>

			<!-- #MAIN CONTENT -->

				
				<!-- col -->
				<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
					<h1 class="page-title txt-color-blueDark">
						
						<!-- PAGE HEADER -->
						<i class="fa-fw fa fa-home"></i> 
							Page Header 
						<span>>  
							Subtitle
						</span>
					</h1>
				</div>
				<!-- end col -->
				

			<!-- end row -->
			
			<!-- END #MAIN CONTENT -->
<% content_for :scripts do %>
// Empty
<% end %>

RubyOnRails_seedProject/app/views/miscellaneous/forgot_password.html.erb
<% content_for :html_id, "extr-page" %>
<% content_for :body_class, "animated fadeInDown" %>
<% content_for :top_right do %>
  <span id="extr-page-header-space"> <span class="hidden-mobile hiddex-xs">Need an account?</span>
    <%= link_to 'Create account', miscellaneous_register_path, class: 'btn btn-danger' %>
  </span>
<% end %>
<!-- MAIN CONTENT -->
<div id="content" class="container">

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-7 col-lg-8 hidden-xs hidden-sm">
      <h1 class="txt-color-red login-header-big">SmartAdmin</h1>
      <div class="hero">

        <div class="pull-left login-desc-box-l">
          <h4 class="paragraph-header">It's Okay to be Smart. Experience the simplicity of SmartAdmin, everywhere you go!</h4>
          <div class="login-app-icons">
            <a href="javascript:void(0);" class="btn btn-danger btn-sm">Frontend Template</a>
            <a href="javascript:void(0);" class="btn btn-danger btn-sm">Find out more</a>
          </div>
        </div>

        <%= image_tag 'demo/iphoneview.png', class: 'pull-right display-image', alt: '', style: 'width:210px' %>

      </div>

      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <h5 class="about-heading">About SmartAdmin - Are you up to date?</h5>
          <p>
            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa.
          </p>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <h5 class="about-heading">Not just your average template!</h5>
          <p>
            Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi voluptatem accusantium!
          </p>
        </div>
      </div>

    </div>
    <div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
      <div class="well no-padding">
        <form action="login.html" id="login-form" class="smart-form client-form">
          <header>
            Forgot Password
          </header>

          <fieldset>

            <section>
              <label class="label">Enter your email address</label>
              <label class="input"> <i class="icon-append fa fa-envelope"></i>
                <input type="email" name="email">
                <b class="tooltip tooltip-top-right"><i class="fa fa-envelope txt-color-teal"></i> Please enter email address for password reset</b></label>
            </section>
            <section>
              <span class="timeline-seperator text-center text-primary"> <span class="font-sm">OR</span></span>
            </section>
            <section>
              <label class="label">Your Username</label>
              <label class="input"> <i class="icon-append fa fa-user"></i>
                <input type="text" name="username">
                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> Enter your username</b> </label>
              <div class="note">
                <a href="login.html">I remembered my password!</a>
              </div>
            </section>

          </fieldset>
          <footer>
            <button type="submit" class="btn btn-primary">
              <i class="fa fa-refresh"></i> Reset Password
            </button>
          </footer>
        </form>

      </div>

      <h5 class="text-center"> - Or sign in using -</h5>

              <ul class="list-inline text-center">
                <li>
                  <a href="javascript:void(0);" class="btn btn-primary btn-circle"><i class="fa fa-facebook"></i></a>
                </li>
                <li>
                  <a href="javascript:void(0);" class="btn btn-info btn-circle"><i class="fa fa-twitter"></i></a>
                </li>
                <li>
                  <a href="javascript:void(0);" class="btn btn-warning btn-circle"><i class="fa fa-linkedin"></i></a>
                </li>
              </ul>

    </div>
  </div>
</div>

RubyOnRails_seedProject/app/views/miscellaneous/locked_screen.html.erb
<% content_for :html_id, "lock-page" %>
<!-- MAIN CONTENT -->

<form class="lockscreen animated flipInY" action="index.html">
  <div class="logo">
    <h1 class="semi-bold"><%= image_tag 'logo-o.png', alt: '' %> SmartAdmin</h1>
  </div>
  <div>
    <%= image_tag 'avatars/sunny-big.png', alt: '', width: '120', height: '120' %>
    <div>
      <h1><i class="fa fa-user fa-3x text-muted air air-top-right hidden-mobile"></i>John Doe <small><i class="fa fa-lock text-muted"></i> &nbsp;Locked</small></h1>
      <p class="text-muted">
        <a href="mailto:simmons@smartadmin">john.doe@smartadmin.com</a>
      </p>

      <div class="input-group">
        <input class="form-control" type="password" placeholder="Password">
        <div class="input-group-btn">
          <button class="btn btn-primary" type="submit">
            <i class="fa fa-key"></i>
          </button>
        </div>
      </div>
      <p class="no-margin margin-top-5">
        Logged as someone else? <a href="login.html"> Click here</a>
      </p>
    </div>

  </div>
  <p class="font-xs margin-top-5">
    Copyright SmartAdmin 2014-2020.

  </p>
</form>